const { PrismaClient } = require('@prisma/client');
const crypto = require('crypto');

const prisma = new PrismaClient();

const mockUmkmList = [
  {
    id: 1,
    nama: "Asep Setiawan",
    nama_usaha: "Bakso Kahuripan",
    produk: "Bakso Solo & Mie Ayam",
    kategori: "Kuliner",
    alamat: "Jl. Kahuripan No. 12",
    rt: 2,
    rw: 5,
    status_nib: "Sudah NIB",
    status_pelatihan: "Pernah",
    desil: 3,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3345,
    longitude: 108.2215
  },
  {
    id: 2,
    nama: "Siti Rahma",
    nama_usaha: "Batik Tasik Cantik",
    produk: "Batik Tulis & Cap Khas Tasik",
    kategori: "Fesyen",
    alamat: "Jl. Siliwangi Gg. Muktamar No. 4",
    rt: 1,
    rw: 3,
    status_nib: "Sudah NIB",
    status_pelatihan: "Pernah",
    desil: 6,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3362,
    longitude: 108.2241
  },
  {
    id: 3,
    nama: "Dadang Hermawan",
    nama_usaha: "Kerajinan Kelom Geulis Dadang",
    produk: "Kelom Geulis (Sandal Kayu)",
    kategori: "Kerajinan",
    alamat: "Jl. BKR No. 45",
    rt: 4,
    rw: 2,
    status_nib: "Sudah NIB",
    status_pelatihan: "Belum",
    desil: 2,
    status_validasi: "Perlu Cek",
    kecamatan: "Tawang",
    tahun_laporan: 2024,
    latitude: -7.3385,
    longitude: 108.2198
  },
  {
    id: 4,
    nama: "Euis Herlina",
    nama_usaha: "Warung Nasi Sunda Ibu Euis",
    produk: "Nasi Timbel & Lauk Pauk",
    kategori: "Kuliner",
    alamat: "Jl. Kahuripan Raya No. 98",
    rt: 3,
    rw: 5,
    status_nib: "Belum NIB",
    status_pelatihan: "Belum",
    desil: 1,
    status_validasi: "Perlu Cek",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3332,
    longitude: 108.2205
  },
  {
    id: 5,
    nama: "Maman Suherman",
    nama_usaha: "Kopi Lokal Tasik",
    produk: "Kopi Bubuk & Minuman Kopi",
    kategori: "Kuliner",
    alamat: "Jl. Tentara Pelajar No. 15",
    rt: 2,
    rw: 4,
    status_nib: "Sudah NIB",
    status_pelatihan: "Pernah",
    desil: 8,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2026,
    latitude: -7.3312,
    longitude: 108.2255
  },
  {
    id: 6,
    nama: "Lilis Karlina",
    nama_usaha: "Roti & Kue Lilis",
    produk: "Roti Manis & Kue Basah",
    kategori: "Kuliner",
    alamat: "Jl. Siliwangi No. 150",
    rt: 5,
    rw: 3,
    status_nib: "Sudah NIB",
    status_pelatihan: "Pernah",
    desil: 5,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3398,
    longitude: 108.2232
  },
  {
    id: 7,
    nama: "Wawan Setiawan",
    nama_usaha: "Wawan Bengkel Las",
    produk: "Jasa Las & Pembuatan Pagar",
    kategori: "Jasa",
    alamat: "Jl. BKR No. 102",
    rt: 1,
    rw: 1,
    status_nib: "Belum NIB",
    status_pelatihan: "Belum",
    desil: 4,
    status_validasi: "Perlu Cek",
    kecamatan: "Tawang",
    tahun_laporan: 2024,
    latitude: -7.3391,
    longitude: 108.2185
  },
  {
    id: 8,
    nama: "Teti Lestari",
    nama_usaha: "Teti Bordir Tasik",
    produk: "Mukena & Kebaya Bordir",
    kategori: "Fesyen",
    alamat: "Jl. Kahuripan No. 5B",
    rt: 2,
    rw: 5,
    status_nib: "Sudah NIB",
    status_pelatihan: "Pernah",
    desil: 7,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3341,
    longitude: 108.2222
  },
  {
    id: 9,
    nama: "Ade Herman",
    nama_usaha: "Budidaya Jamur Tiram Ade",
    produk: "Jamur Tiram Segar",
    kategori: "Pertanian",
    alamat: "Gg. Kahuripan III No. 17",
    rt: 3,
    rw: 6,
    status_nib: "Belum NIB",
    status_pelatihan: "Belum",
    desil: 2,
    status_validasi: "Perlu Cek",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3325,
    longitude: 108.2178
  },
  {
    id: 10,
    nama: "Cecep Mulyana",
    nama_usaha: "Keripik Tempe Cecep",
    produk: "Keripik Tempe Aneka Rasa",
    kategori: "Kuliner",
    alamat: "Jl. Siliwangi Gg. H. Gofur",
    rt: 3,
    rw: 3,
    status_nib: "Sudah NIB",
    status_pelatihan: "Belum",
    desil: 3,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3371,
    longitude: 108.2259
  },
  {
    id: 11,
    nama: "Diana Putri",
    nama_usaha: "Diana Salon & Wedding",
    produk: "Jasa Rias Pengantin & Potong Rambut",
    kategori: "Jasa",
    alamat: "Jl. Tentara Pelajar No. 64",
    rt: 1,
    rw: 4,
    status_nib: "Sudah NIB",
    status_pelatihan: "Pernah",
    desil: 9,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2026,
    latitude: -7.3305,
    longitude: 108.2268
  },
  {
    id: 12,
    nama: "Endang Kosasih",
    nama_usaha: "Endang Mebel Kayu",
    produk: "Kursi, Lemari & Meja Kayu",
    kategori: "Kerajinan",
    alamat: "Jl. BKR No. 12B",
    rt: 4,
    rw: 2,
    status_nib: "Belum NIB",
    status_pelatihan: "Belum",
    desil: 3,
    status_validasi: "Perlu Cek",
    kecamatan: "Tawang",
    tahun_laporan: 2024,
    latitude: -7.3389,
    longitude: 108.2201
  },
  {
    id: 13,
    nama: "Imas Masriah",
    nama_usaha: "Catering Barokah Ibu Imas",
    produk: "Nasi Kotak & Prasmanan",
    kategori: "Kuliner",
    alamat: "Gg. Kahuripan IV No. 3",
    rt: 4,
    rw: 5,
    status_nib: "Sudah NIB",
    status_pelatihan: "Pernah",
    desil: 5,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3351,
    longitude: 108.2208
  },
  {
    id: 14,
    nama: "Hendra Wijaya",
    nama_usaha: "Kahuripan Print & Fotocopy",
    produk: "Jasa Cetak & Fotocopy",
    kategori: "Jasa",
    alamat: "Jl. Siliwangi No. 182",
    rt: 2,
    rw: 3,
    status_nib: "Sudah NIB",
    status_pelatihan: "Belum",
    desil: 7,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3382,
    longitude: 108.2238
  },
  {
    id: 15,
    nama: "Yanti Susianti",
    nama_usaha: "Yanti Rajutan Kreatif",
    produk: "Tas & Dompet Rajut",
    kategori: "Kerajinan",
    alamat: "Jl. Siliwangi No. 210",
    rt: 5,
    rw: 3,
    status_nib: "Sudah NIB",
    status_pelatihan: "Pernah",
    desil: 6,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3395,
    longitude: 108.2248
  },
  {
    id: 16,
    nama: "Usep Rustandi",
    nama_usaha: "Tahu Sumedang Tawang",
    produk: "Tahu Goreng Gurih",
    kategori: "Kuliner",
    alamat: "Jl. Tentara Pelajar No. 44",
    rt: 3,
    rw: 4,
    status_nib: "Belum NIB",
    status_pelatihan: "Belum",
    desil: 4,
    status_validasi: "Perlu Cek",
    kecamatan: "Tawang",
    tahun_laporan: 2026,
    latitude: -7.3318,
    longitude: 108.2261
  },
  {
    id: 17,
    nama: "Neneng Hasanah",
    nama_usaha: "Neneng Hijab Mode",
    produk: "Pashmina, Segi Empat & Abaya",
    kategori: "Fesyen",
    alamat: "Jl. Kahuripan No. 41",
    rt: 1,
    rw: 5,
    status_nib: "Sudah NIB",
    status_pelatihan: "Pernah",
    desil: 8,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3348,
    longitude: 108.2229
  },
  {
    id: 18,
    nama: "Jajang Nurjaman",
    nama_usaha: "Jajang Sol Sepatu",
    produk: "Jasa Reparasi Sandal & Sepatu",
    kategori: "Jasa",
    alamat: "Jl. BKR No. 66",
    rt: 3,
    rw: 2,
    status_nib: "Belum NIB",
    status_pelatihan: "Belum",
    desil: 2,
    status_validasi: "Perlu Cek",
    kecamatan: "Tawang",
    tahun_laporan: 2024,
    latitude: -7.3382,
    longitude: 108.2192
  },
  {
    id: 19,
    nama: "Ira Mayasari",
    nama_usaha: "Ira Kue Kering Khas Tasik",
    produk: "Kue Kering, Nastar & Kastengel",
    kategori: "Kuliner",
    alamat: "Gg. Kahuripan V No. 9",
    rt: 2,
    rw: 5,
    status_nib: "Sudah NIB",
    status_pelatihan: "Pernah",
    desil: 5,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3355,
    longitude: 108.2220
  },
  {
    id: 20,
    nama: "Komarudin",
    nama_usaha: "Komar Mebel Bambu",
    produk: "Kursi & Kursi Goyang Bambu",
    kategori: "Kerajinan",
    alamat: "Jl. BKR No. 132",
    rt: 2,
    rw: 1,
    status_nib: "Sudah NIB",
    status_pelatihan: "Belum",
    desil: 4,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2024,
    latitude: -7.3396,
    longitude: 108.2189
  },
  {
    id: 21,
    nama: "H. Encep",
    nama_usaha: "Sandal Payung Geulis H. Encep",
    produk: "Payung Geulis Tradisional",
    kategori: "Kerajinan",
    alamat: "Jl. Siliwangi No. 101",
    rt: 4,
    rw: 3,
    status_nib: "Sudah NIB",
    status_pelatihan: "Pernah",
    desil: 10,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3368,
    longitude: 108.2235
  },
  {
    id: 22,
    nama: "Yusuf Mansur",
    nama_usaha: "Yusuf Percetakan Undangan",
    produk: "Undangan & Buku Yasin",
    kategori: "Jasa",
    alamat: "Jl. Siliwangi No. 191",
    rt: 3,
    rw: 3,
    status_nib: "Belum NIB",
    status_pelatihan: "Belum",
    desil: 5,
    status_validasi: "Perlu Cek",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3386,
    longitude: 108.2243
  },
  {
    id: 23,
    nama: "Siti Maryam",
    nama_usaha: "Siti Rengginang Enak",
    produk: "Rengginang Ketan Asli",
    kategori: "Kuliner",
    alamat: "Gg. Kahuripan I No. 44",
    rt: 1,
    rw: 5,
    status_nib: "Sudah NIB",
    status_pelatihan: "Pernah",
    desil: 3,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3338,
    longitude: 108.2210
  },
  {
    id: 24,
    nama: "Ujang Ruhiat",
    nama_usaha: "Ujang Cuci Motor",
    produk: "Jasa Cuci Motor & Helm",
    kategori: "Jasa",
    alamat: "Jl. BKR No. 15",
    rt: 3,
    rw: 2,
    status_nib: "Belum NIB",
    status_pelatihan: "Belum",
    desil: 4,
    status_validasi: "Perlu Cek",
    kecamatan: "Tawang",
    tahun_laporan: 2024,
    latitude: -7.3378,
    longitude: 108.2195
  },
  {
    id: 25,
    nama: "Eny Lestari",
    nama_usaha: "Eny Hijab Anak",
    produk: "Jilbab Anak & Gamis Balita",
    kategori: "Fesyen",
    alamat: "Jl. Kahuripan No. 67",
    rt: 3,
    rw: 5,
    status_nib: "Sudah NIB",
    status_pelatihan: "Pernah",
    desil: 6,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3353,
    longitude: 108.2227
  },
  {
    id: 26,
    nama: "Nandar Rahman",
    nama_usaha: "Nandar Peternak Lele",
    produk: "Lele Konsumsi Segar",
    kategori: "Pertanian",
    alamat: "Gg. Kahuripan VI No. 10",
    rt: 4,
    rw: 6,
    status_nib: "Belum NIB",
    status_pelatihan: "Belum",
    desil: 3,
    status_validasi: "Perlu Cek",
    kecamatan: "Tawang",
    tahun_laporan: 2026,
    latitude: -7.3330,
    longitude: 108.2182
  },
  {
    id: 27,
    nama: "Iman Nurjaman",
    nama_usaha: "Iman Keripik Singkong",
    produk: "Keripik Singkong Renyah",
    kategori: "Kuliner",
    alamat: "Jl. Tentara Pelajar No. 11",
    rt: 1,
    rw: 4,
    status_nib: "Sudah NIB",
    status_pelatihan: "Pernah",
    desil: 4,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2026,
    latitude: -7.3298,
    longitude: 108.2250
  },
  {
    id: 28,
    nama: "Rita Rosita",
    nama_usaha: "Rita Rias Pengantin",
    produk: "Jasa Rias & Persewaan Baju",
    kategori: "Jasa",
    alamat: "Jl. Siliwangi No. 122",
    rt: 2,
    rw: 3,
    status_nib: "Sudah NIB",
    status_pelatihan: "Pernah",
    desil: 8,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3375,
    longitude: 108.2239
  },
  {
    id: 29,
    nama: "Lukman Hakim",
    nama_usaha: "Lukman Kerajinan Kayu Mainan",
    produk: "Mainan Edukatif Kayu",
    kategori: "Kerajinan",
    alamat: "Jl. BKR No. 72",
    rt: 4,
    rw: 2,
    status_nib: "Belum NIB",
    status_pelatihan: "Belum",
    desil: 2,
    status_validasi: "Perlu Cek",
    kecamatan: "Tawang",
    tahun_laporan: 2024,
    latitude: -7.3384,
    longitude: 108.2190
  },
  {
    id: 30,
    nama: "Cucu Cahyati",
    nama_usaha: "Cucu Jahit Busana",
    produk: "Jasa Permak & Jahit Pakaian",
    kategori: "Fesyen",
    alamat: "Jl. Kahuripan Gg. Family No. 2",
    rt: 2,
    rw: 5,
    status_nib: "Sudah NIB",
    status_pelatihan: "Belum",
    desil: 5,
    status_validasi: "Cek Lapangan",
    kecamatan: "Tawang",
    tahun_laporan: 2025,
    latitude: -7.3343,
    longitude: 108.2218
  }
];

async function main() {
  const username = 'admin';
  const rawPassword = 'admin123';
  const hashedPassword = crypto.createHash('sha256').update(rawPassword).digest('hex');
  const nama = 'Administrator BAKUL';

  console.log('Seeding default administrator account...');

  const admin = await prisma.admin.upsert({
    where: { username },
    update: {
      password: hashedPassword,
      nama,
    },
    create: {
      username,
      password: hashedPassword,
      nama,
    },
  });

  console.log(`Seeded admin account successfully: ${admin.username}`);

  console.log('Seeding default UMKM data...');
  for (const item of mockUmkmList) {
    await prisma.umkm.upsert({
      where: { id: item.id },
      update: item,
      create: item,
    });
  }
  console.log('Seeded all UMKM data successfully.');
}

main()
  .catch((e) => {
    console.error('Error seeding data:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
